# Generated by Django 4.1.5 on 2023-01-31 19:02

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_actor_product_actor_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
        migrations.AddField(
            model_name='actor',
            name='parent',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='children', to='products.actor'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='children', to='products.category'),
        ),
    ]
