# Generated by Django 4.1.5 on 2023-02-01 18:33

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actor',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='actor', to='products.actor', verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, null=True, related_name='category', to='products.category', verbose_name='category'),
        ),
    ]
